language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "6"
install: true
before_script:
  - npm i -g npm@5.6.0
  - npm i -g webpack@3.10.0
  - npm install
script:
  - npm run test
  - npm run prod
deploy:
  provider: heroku
  api_key:
    secure: ...
  app: lovedota-nytimes
  skip_cleanup: true
